#!/usr/bin/env python3
"""Prototype generator for lookup tables.

Reads a CSV of `codepoint_hex,replacement` lines and generates a Gleam
module that exposes a `translit_lookup(codepoint: Int) -> Option(String)`.

This is a prototype: later versions will generate compact BitArray literals
and a two-level index like string-width.

Usage:
  ./scripts/generate_bitarray_tables.py --input data/translit.csv --out src/str/internal/generated_translit_table.gleam --module str/internal/generated_translit_table --name translit_map

If no input is provided the script emits a small sample mapping.
"""
import argparse
import csv
import sys

SAMPLE = [
    (0x00C0, "A"),  # À
    (0x00C1, "A"),  # Á
    (0x00E0, "a"),  # à
    (0x00E9, "e"),  # é
]

TEMPLATE = """// Generated by scripts/generate_bitarray_tables.py
// Module: {module}

import gleam/dict

pub const {name}_pairs: List(#(Int, String)) = [
{pairs}
]

pub fn {name}_lookup(cp: Int) -> Result(String, Nil) {{
  let d = dict.from_list({name}_pairs)
  case dict.get(d, cp) {{
    Ok(v) -> Ok(v)
    Error(_) -> Error(Nil)
  }}
}}
"""


def read_csv(path):
    pairs = []
    with open(path, newline="") as f:
        r = csv.reader(f)
        for row in r:
            if not row:
                continue
            h = row[0].strip()
            val = row[1].strip() if len(row) > 1 else ""
            try:
                cp = int(h, 16) if h.startswith("0x") or h.startswith("0X") else int(h, 16)
            except Exception:
                # try parse as hex without prefix
                cp = int(h, 16)
            pairs.append((cp, val))
    return pairs


def format_pairs(pairs):
    lines = []
    for cp, val in pairs:
        lines.append(f"  #({hex(cp)}, \"{val}\"),")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--input", help="CSV input file (codepoint_hex,replacement)")
    p.add_argument("--out", help="Output Gleam file path (defaults to stdout)")
    p.add_argument("--module", help="Gleam module name (for comments)")
    p.add_argument("--name", help="Base name for generated constants", default="translit_map")
    args = p.parse_args()

    if args.input:
        pairs = read_csv(args.input)
    else:
        pairs = SAMPLE

    pairs_str = format_pairs(pairs)
    module = args.module or "generated_translit_table"
    out = TEMPLATE.format(module=module, name=args.name, pairs=pairs_str)

    if args.out:
        with open(args.out, "w") as f:
            f.write(out)
        print(f"Wrote {args.out}")
    else:
        print(out)


if __name__ == "__main__":
    main()
