// Generated by scripts/generate_bitarray_tables.py
// Module: str/internal/generated_translit_table

import gleam/dict

pub const translit_map_pairs: List(#(Int, String)) = [
  #(0xc0, "A"),
  #(0xc1, "A"),
  #(0xe0, "a"),
  #(0xe9, "e"),
]

pub fn translit_map_lookup(cp: Int) -> Result(String, Nil) {
  let d = dict.from_list(translit_map_pairs)
  case dict.get(d, cp) {
    Ok(v) -> Ok(v)
    Error(_) -> Error(Nil)
  }
}
